[package]
name = "calcr"
version = "0.5.5"
authors = ["ph04 <alessio.bandiera02@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
quit = "1.1.4"
clearscreen = "1.0.4"
structopt = "0.3"